import { View, TextInput, Text, Keyboard, Pressable, KeyboardAvoidingView, Platform } from 'react-native'
import { Ionicons } from '@expo/vector-icons';

export default function Budget(){
    
    //Pressable must fill whole screen or dismiss wont work
    //TODO: widths of stuff is hardcoded right now, fix this as you scale up
    //TODO: This amount isn't saved anywhere at the moment. Be sure to connect this info into the control flow of the rest of the app

    return ( 
        <Pressable style={{flex: 1}} onPress={() => {Keyboard.dismiss()}}>
            <BudgetInput />
            <ExplainerText />
        </Pressable>
    )
}

function BudgetInput(){
    return(
        <View style={{paddingTop: 100}}>
            <Text>Budget</Text>
            <View style={{flexDirection: 'row'}}>
                <Text style={{alignSelf: 'center'}}>$</Text>
                <TextInput 
                style={{width: 375, height: 40, borderWidth: 1}}
                onPressIn={() => Keyboard.isVisible()}
                keyboardType='numeric'
                placeholder='0.00'
                />
            </View>
        </View>
    )
}

function ExplainerText(){
    return (
        <View style={{flexDirection: 'row'}}>
            <Ionicons style={{width: 25}}name="ios-information-circle-outline" size={24} color="black" />
            <Text style={{width: 350}}>This budget will be generated by the AI and is a suggested amount based on the information that you previously entered. However, you can edit your budget above</Text>
        </View>
    )
}