import { View, TextInput, Text, Keyboard, Pressable, KeyboardAvoidingView, Platform } from 'react-native'
import { Ionicons } from '@expo/vector-icons';
import { blockStyles } from '../../../utils/styles/BlockStyles';
import PrimaryButton from '../../../components/common/PrimaryButton';
import { IconBlockTypes, PrimaryButtonTypes } from '../../../utils/advent-types';
import { textStyles } from '../../../utils/styles/TextStyles';
import TextField from '../../../components/common/TextField';
import { TextFieldStyles } from '../../../utils/styles/TextFieldStyles';
import IconBlock from '../../../components/common/IconBlock';
import { useState } from 'react';

export default function Budget(){
    //Pressable must fill whole screen or dismiss wont work
    const [budget, setBudget] = useState<number>()

    return ( 
        <>
            <Pressable style={{flex: 1}} onPress={() => {Keyboard.dismiss()}}>
                <View style={blockStyles.block}>
                    <View style={blockStyles.innerBlock}>
                        <BudgetInput callback={(budget: number) => setBudget(budget)}/>
                        <ExplainerText />
                    </View>
                </View>
            </Pressable>
            <PrimaryButton title={PrimaryButtonTypes.checkout} isPressed={() => console.log('#TODO: Implement linking')}/>
        </>
        
    )
}

function BudgetInput({ callback }){
    return(
        <View style={{marginVertical: 7}}>
            <Text style={textStyles.secondaryButtonText}>Budget</Text>
            <TextField style={TextFieldStyles.singleLineInput} defaultText='100.00USD' keyboard='decimal' currentText={(text) => callback(text)}/>
        </View>
    )
}

function ExplainerText(){
    return (
        <IconBlock icon={IconBlockTypes.info} text='This budget will be generated by the AI and is a suggested amount based on the information that you previously entered. However, you can edit your budget above' />
    )
}