export const states: Array<object> = [
    { key: 1, state: 'AL', name: 'Alabama' },
    { key: 2, state: 'AK', name: 'Alaska' },
    { key: 3, state: 'AZ', name: 'Arizona' },
    { key: 4, state: 'AR', name: 'Arkansas' },
    { key: 5, state: 'CA', name: 'California' },
    { key: 6, state: 'CO', name: 'Colorado' },
    { key: 7, state: 'CT', name: 'Connecticut' },
    { key: 8, state: 'DE', name: 'Delaware' },
    { key: 9, state: 'FL', name: 'Florida' },
    { key: 10, state: 'GA', name: 'Georgia' },
    { key: 11, state: 'HI', name: 'Hawaii' },
    { key: 12, state: 'ID', name: 'Idaho' },
    { key: 13, state: 'IL', name: 'Illinois' },
    { key: 14, state: 'IN', name: 'Indiana' },
    { key: 15, state: 'IA', name: 'Iowa' },
    { key: 16, state: 'KS', name: 'Kansas' },
    { key: 17, state: 'KY', name: 'Kentucky' },
    { key: 18, state: 'LA', name: 'Louisiana' },
    { key: 19, state: 'ME', name: 'Maine' },
    { key: 20, state: 'MD', name: 'Maryland' },
    { key: 21, state: 'MA', name: 'Massachusetts' },
    { key: 22, state: 'MI', name: 'Michigan' },
    { key: 23, state: 'MN', name: 'Minnesota' },
    { key: 24, state: 'MS', name: 'Mississippi' },
    { key: 25, state: 'MO', name: 'Missouri' },
    { key: 26, state: 'MT', name: 'Montana' },
    { key: 27, state: 'NE', name: 'Nebraska' },
    { key: 28, state: 'NV', name: 'Nevada' },
    { key: 29, state: 'NH', name: 'New Hampshire' },
    { key: 30, state: 'NJ', name: 'New Jersey' },
    { key: 31, state: 'NM', name: 'New Mexico' },
    { key: 32, state: 'NY', name: 'New York' },
    { key: 33, state: 'NC', name: 'North Carolina' },
    { key: 34, state: 'ND', name: 'North Dakota' },
    { key: 35, state: 'OH', name: 'Ohio' },
    { key: 36, state: 'OK', name: 'Oklahoma' },
    { key: 37, state: 'OR', name: 'Oregon' },
    { key: 38, state: 'PA', name: 'Pennsylvania' },
    { key: 39, state: 'RI', name: 'Rhode Island' },
    { key: 40, state: 'SC', name: 'South Carolina' },
    { key: 41, state: 'SD', name: 'South Dakota' },
    { key: 42, state: 'TN', name: 'Tennessee' },
    { key: 43, state: 'TX', name: 'Texas' },
    { key: 44, state: 'UT', name: 'Utah' },
    { key: 45, state: 'VT', name: 'Vermont' },
    { key: 46, state: 'VA', name: 'Virginia' },
    { key: 47, state: 'WA', name: 'Washington' },
    { key: 48, state: 'WV', name: 'West Virginia' },
    { key: 49, state: 'WI', name: 'Wisconsin' },
    { key: 50, state: 'WY', name: 'Wyoming' },
  ];
  